# Script for Programming system generation
all: komppl kompassr absloadm
#komppl.o: komppl.c
#	gcc -o komppl.o komppl.c
komppl: komppl.c
	@echo "komppl"
	gcc -o komppl.out komppl.c
	@echo "ok"
kompassr: kompassr.c
	@echo "kompassr"
	gcc -o kompassr.out kompassr.c
	@echo "ok"
absloadm: absloadm.c
	@echo "absloadm"
	g++ absloadm.c -lncurses -o absloadm.out 
	@echo "ok"

