#!/bin/bash

echo
echo "______________S T A R T   J O B_____________________"
echo
echo ' PL/1  ----->  Asswmbler    c o m p i l i n g'
echo "continue?(y/n)"
read OTV
if [ $OTV = "y" ] 
then
 echo
 ./kpl.out  $1.pli
fi

echo
echo ' Assembler  ----->  Object image   c o m p i l i n g'
echo "continue?(y/n)"
read OTV
if [ $OTV = "y" ] 
then
 echo
./kass.out $1.ass
fi

echo
echo ' Load, run and debug Object image  '
echo "continue?(y/n)"
read OTV
if [ $OTV = "y" ] 
then
 echo
./load.out spis.mod
fi

echo
echo "______________F I N I S H     J O B__________________"
